# Generated by Django 5.2.7 on 2026-06-19 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Master project name', max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this project is active and available to workers')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Camp or accommodation block name', max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this location is active and select-able')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(help_text='Associated project', on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='api.project')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('project', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(help_text='Issue category (e.g. water, electricity, toilet)', max_length=50)),
                ('language', models.CharField(help_text='Worker language code (e.g. en, hi, ta)', max_length=10)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved'), ('Rejected', 'Rejected')], default='Pending', help_text='Current complaint status', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('photo_url', models.URLField(blank=True, help_text='Cloudinary or AWS S3 image storage URL', max_length=500, null=True)),
                ('audio_url', models.URLField(blank=True, help_text='Cloudinary or AWS S3 audio recording URL', max_length=500, null=True)),
                ('original_text', models.TextField(blank=True, help_text='Speech-to-text transcript in original language', null=True)),
                ('english_translation', models.TextField(blank=True, help_text='English translation of transcript/comments', null=True)),
                ('reference_number', models.CharField(help_text='Tracking ticket format: CMP-YYYY-XXXXX', max_length=50, unique=True)),
                ('location', models.ForeignKey(help_text='Specific camp area or block', on_delete=django.db.models.deletion.PROTECT, related_name='complaints', to='api.location')),
                ('project', models.ForeignKey(help_text='Project where issue occurred', on_delete=django.db.models.deletion.PROTECT, related_name='complaints', to='api.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
