# Generated by Django 5.2.7 on 2026-06-20 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_complaint_audio_duration_seconds_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='speech_processing_duration_ms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='translation_confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='translation_language_pair',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='translation_verification_result',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='worker_selected_language',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='localized_names',
            field=models.JSONField(blank=True, default=dict, help_text='Language translations for location name'),
        ),
        migrations.AddField(
            model_name='project',
            name='localized_names',
            field=models.JSONField(blank=True, default=dict, help_text='Language translations for project name'),
        ),
        migrations.AddField(
            model_name='speechprocessinglog',
            name='verification_result',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='speechprocessinglog',
            name='verification_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
